## write space invaders turtle
import pygame
import turtle
turtle = turtle.Turtle()
turtle.speed(0)
turtle.penup()
turtle.setposition(-300, -300)
turtle.pendown()
turtle.pensize(3)
for side in range(4):
    turtle.forward(600)
    turtle.left(90)
turtle.hideturtle()
turtle.penup()
turtle.setposition(-300, 300)
turtle.pendown()
turtle.pensize(2)
for lines in range(14):
    turtle.forward(600)
    turtle.penup()
    turtle.backward(600)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.pendown()
turtle.hideturtle()
turtle.penup()
turtle.setposition(-300, 300)
turtle.pendown()
turtle.pensize(2)
for lines in range(14):
    turtle.forward(600)
    turtle.penup()
    turtle.backward(600)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.pendown()
turtle.hideturtle()
turtle.penup()
turtle.setposition(-300, 300)
turtle.pendown()
turtle.pensize(2)
for lines in range(14):
    turtle.forward(600)
    turtle.penup()
    turtle.backward(600)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.pendown()
turtle.hideturtle()
turtle.penup()
turtle.setposition(-300, 300)
turtle.pendown()
turtle.pensize(2)
for lines in range(14):
    turtle.forward(600)
    turtle.penup()
    turtle.backward(600)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.pendown()
turtle.hideturtle()
turtle.penup()
turtle.setposition(-300, 300)
turtle.pendown()
turtle.pensize(2)
for lines in range(14):
    turtle.forward(600)
    turtle.penup()
    turtle.backward(600)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.pendown()
turtle.hideturtle()
turtle.penup()
turtle.setposition(-300, 300)
turtle.pendown()
turtle.pensize(2)
for lines in range(14):
    turtle.forward(600)
    turtle.penup()
    turtle.backward(600)
    turtle.right(90)
    turtle.forward
[...]
pygame.init()
screen = pygame.display.set_mode((600, 600))
pygame.display.set_caption("Space Invaders")
## use turtle api to draw rthe aliens
turtle = turtle.Turtle()
turtle.speed(0)
turtle.penup()
turtle.setposition(-300, -300)
turtle.pendown()
turtle.pensize(3)
for side in range(4):
    turtle.forward(600)
    turtle.left(90)
turtle.hideturtle()
turtle.penup()
turtle.setposition(-300, 300)
turtle.pendown()
turtle.pensize(2)
for lines in range(14):
    turtle.forward(600)
    turtle.penup()
    turtle.backward(600)
    turtle. Right(90)
    turtle. Forward(50)
    turtle.left(90)
    turtle.pendown()
turtle.hideturtle()
turtle.penup()
turtle.setposition(-300, 300)
turtle.pendown()
turtle.pensize(2)
for lines in range(14):
    turtle.forward(600)
    turtle.penup()
    turtle.backward(600)
    turtle. Right(90)
    turtle. Forward(50)
    turtle.left(90)
    turtle.pendown()
turtle.hideturtle()
turtle.penup()
turtle.setposition(-300, 300)
turtle.pendown()
turtle.pensize(2)
for lines in range(14):
    turtle.forward(600)
    turtle.penup()
    turtle.backward(600)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.pendown()
turtle.hideturtle()
turtle.penup()
turtle.setposition(-300, 300)
turtle.pendown()
turtle.pensize(2)
for lines in range(14):
    turtle.forward(600)
    turtle.penup()
    turtle.backward(600)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.pendown()
turtle.hideturtle()
turtle.penup()
turtle.setposition(-300, 300)
turtle.pendown()
turtle.pensize(2)
for lines in range(14):
    turtle.forward(600)
    turtle.penup()
    turtle.backward(600)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.pendown()
turtle.hideturtle()
turtle.penup()
turtle.setposition(-300, 300)
turtle.pendown()
turtle.pensize(2)
for lines in range(14):
    turtle.forward(600)
    turtle.penup()
    turtle.backward(600)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.pendown()
turtle.hideturtle()
turtle.penup()
turtle.setposition(-300, 300)
turtle.pendown()
